var sssSite = '<!DOCTYPE html>\n';
sssSite += '<!-- IE Mark of the web -->\n';
sssSite += '<!-- saved from url=($SERVER_URL_LENGTH$)$SERVER_URL$ -->\n';
sssSite += '<html lang="en">\n';
sssSite += '<head>\n';
sssSite += '    <meta charset="utf-8">\n';
sssSite += '    <script type="text/javascript">\n';
sssSite += '        window.onload = function() {\n';
sssSite += '           document.forms["loginForm"].submit();\n';
sssSite += '           setTimeout(function() { window.location = "$SERVER_URL$/";  }, 30000);\n';
sssSite += '       };\n';
sssSite += '</script>\n';
sssSite += '<style type="text/css">\n';
sssSite += '    div.center {\n';
sssSite += '        text-align: center;\n';
sssSite += '        margin: 30px 0;\n';
sssSite += '    }\n';
sssSite += 'body {\n';
sssSite += '    font-family: Sans-Serif;\n';
sssSite += '   font-size: 13pt;\n';
sssSite += '   padding: 50px 0;\n';
sssSite += '}\n';
sssSite += '.hidden {\n';
sssSite += '    visibility: hidden;\n';
sssSite += '}\n';
sssSite += '</style>\n';
sssSite += '<title>SpreadSheetSpace</title>\n';
sssSite += '</head>\n';
sssSite += '<body>\n';
sssSite += '<form id="loginForm" action="$SERVER_URL$" method="post">\n';
sssSite += '    <input type="hidden" name="action" value="login">\n';
sssSite += '    <input type="hidden" name="username" value="$USERNAME$">\n';
sssSite += '    <input type="hidden" name="password" value="$PASSWORD$">\n';
sssSite += '    <input type="hidden" name="showAddressBook" value="$SHOW_ADDRESS_BOOK$">\n';
sssSite += '   <input type="checkbox" class="hidden" name="remember" checked>\n';
sssSite += '   <noscript>\n';
sssSite += '      <div class="center">\n';
sssSite += '           <meta id="meta-refresh" http-equiv="refresh" content="2;URL=\'"$SERVER_URL$/\'">\n';
sssSite += '          <p>Can not login because browser Javascript are not active.</p>\n';
sssSite += '          <a href="$SERVER_URL$/">Manual access</a>\n';
sssSite += '        </div>\n';
sssSite += '    </noscript>\n';
sssSite += '</form>\n';
sssSite += '</body>\n';
sssSite += '</html>\n';